services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - laravel-network

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    command: --mysql-native-password=ON
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - laravel-network

  queue:
    image: laravel-app
    container_name: laravel-queue
    restart: unless-stopped
    env_file:
      - .env
    command: [ "php", "artisan", "queue:work", "--tries=3" ]
    depends_on:
      - app
      - mysql
      - redis
    networks:
      - laravel-network

volumes:
  db-data:

networks:
  laravel-network:
    driver: bridge